# Database connection details
# Actualizado al puerto 15029 (MySQL Clásico) según el Service URI de Aiven
spring.datasource.url=jdbc:mysql://mysql-291cc8ba-uqvirtual-cb32.d.aivencloud.com:15029/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_zTnaJYyszmu-tw0cakp

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Boot common properties
server.port=8080
spring.application.name=solicitudes-academicas
